# Generated by Django 3.2.11 on 2022-01-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('value', models.TextField(blank=True, null=True)),
                ('type', models.PositiveIntegerField(choices=[(1, 'integer'), (2, 'string'), (3, 'float')], default=2)),
                ('nullable', models.BooleanField(default=False)),
            ],
        ),
    ]
