# Generated by Django 3.2.11 on 2022-01-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
